app_host: 'https://37ae2cc5.ngrok.io'

encryption_key1: 'This is a key that is 256 bits!!'
encryption_key2: 'This is a key that is 256 bits!!'

default:
  environment: 'local'
  api_host: 'http://localhost:5678'

maestrano-uat:
  environment: 'local'
  api_host: 'http://localhost:5678'
